// Generated by `npm run photos`. Do not edit by hand.
import type { VehicleImage } from "./types";

export const photos: Record<string, VehicleImage[]> = {
  "1989-chevrolet-camaro-rs": [
    {
      "src": "/inventory/1989-chevrolet-camaro-rs/01.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwAgCdASoQAAwAA4BaJZACdAD8v8QOkif/AAD+QT7Wrhv4uMWKqWH7h6v5cuTg/Gf9Vz+9Qq/GaxlL36klPcgyBXSaCeymcljHFvKKpjCg8d+GkWlgBu0JFKvwm453GuwAAA=="
    },
    {
      "src": "/inventory/1989-chevrolet-camaro-rs/02.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAACwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JagCdMoAluxldzWukAXFNW74MM72gAP6DoYH/3J2zZ2OOyGCaQkYr14YodLNEt7KmPYHkp4ZLHoatNUQKO+NfGosMuMjXjWAwV1UubIASgnUntLl+LBwqT3hB3VdcdgIwY0AlHPAWORKxzLGLoqgnAwNH/M5fhUYxEPC60jnlC/VfjFZCn3nWwAA="
    },
    {
      "src": "/inventory/1989-chevrolet-camaro-rs/03.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAABwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdISB4ABOb+w/BMe7h3qYYgAD+qtpE+9FN+8QRQCQqgZ3ILgoUxCBVadejsmZvJY3jqco+02qgBBY2BJAHD6miO2OMo0YN9Bjz1spKW55pI1ZZJVoUjErWE7eXPg3VDg6q4zIf4LctSV+6DKkdi+vbu0waGYl/n7TN5XBUpjYsHT05qiAYVgFcyxWAAAA="
    },
    {
      "src": "/inventory/1989-chevrolet-camaro-rs/04.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAQCdASoQAAwAA4BaJaACdAEDEd3MwAD9cHllZ/MHbK06lDRzBbu77LAnUAfaVsfVO5VqiHJjnv4BT+W2/K8wvRJ4AWYPvX1ploGQr0Pdy8+IJvu6vC++wEVoPzVFSM4AAA=="
    },
    {
      "src": "/inventory/1989-chevrolet-camaro-rs/05.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAQCdASoQAAwAA4BaJQBOgB9HY+7IAAD+6kg/P4FKXwhgj/yC6wWaa0O2UGTMGtI9mkISvuk35H7TgwELd6TACWqeNUCIi0WPU9ACKYVoosZbIdDrruI3GUzwQAAA"
    },
    {
      "src": "/inventory/1989-chevrolet-camaro-rs/06.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAwAA4BaJYgCdAELMliPEAAA/qN8NkZTsyee2dIi1FeuBdobbeXqn/hxp2v1wHDrBNFQXFzdfanc+2eM8R+8KAco4m0bVYIoASIFOQAAAA=="
    },
    {
      "src": "/inventory/1989-chevrolet-camaro-rs/07.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAwAA4BaJagCdACoP1HD/8AA+6H/Dh1Y5UL0cfZmOdV1P1itEO66bsx0MLS0w34++Ave2WSj/DMB5aExzCDbDI38IP2KBzVUKHNPkABu5h7N89tAAA=="
    },
    {
      "src": "/inventory/1989-chevrolet-camaro-rs/08.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAABwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYgCsMoADZw5BfTYf9qIE3oI8AAD8D1oCjD23RBRkG63U1yCa1Dj8AxifxGf8OhXOx6gkslpjzW/bOG4pQ5V2Ck/Fz04E+O9caWYPgVZbNXXxH/0FpsEcqNOV+xviGmJbdIkTK3Gs+ds62CoC+LG9br0kIIXlLVTvvOfpCtonl+jWnsvAaeeZPY/+KQzQ4nNF+v/yAAAAAA=="
    },
    {
      "src": "/inventory/1989-chevrolet-camaro-rs/09.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABQAgCdASoQAAwAA4BaJQBOgMWR7aQyREkX4QAA/bCh4bJ2ko2B+g3bNVSJrxzOputuH/LhO0Y55FFtjROHVrcFbgfhMS4yf681WnDyr1CU7pJ+HvrluDwvAo2D2keUKkMRAGny5knAAA=="
    },
    {
      "src": "/inventory/1989-chevrolet-camaro-rs/10.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAwAA4BaJZwC7AEO9Pxha/IAAP5OZT4mJusZSQ2Kb6Kz5byJHyuzfTR0Tz7mH013RPLs9k6Lrtn1spIjYmXY9ChBjFQzuXY+cNytM8QAAA=="
    },
    {
      "src": "/inventory/1989-chevrolet-camaro-rs/11.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAADQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JaADE2YwSpXsHwKcXbOAAzj6beUU+pB1MROKcog0gQwIkPtSitGYXjE3Nku4HHC+0Et5wvML0BFVElNeN40z0VAaJmGsLom2wXl2bAG3YA47miD9f445HMJcLUUuG14mgWl9wxoPOh9HrHfv+Um5Wf7JGHtM9I00Rvf1iky97DuAmfQxCbBP7/36PnVX+lRz/S6AA"
    },
    {
      "src": "/inventory/1989-chevrolet-camaro-rs/12.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQAB8n0HNXgnzzUa33fObF9gAy0j9S9OnQBPfbL1/a1XaRj8OWXZlu1IDvRh/XM7LMWZz6VEoYKHtsuqh2NaJYNCxl+AAC+wASJum3ZtMkmggGF25chCILf7iEZUv3j1pVXg/m8Tqf9sHwKn0gMTKBPJrwAAA"
    },
    {
      "src": "/inventory/1989-chevrolet-camaro-rs/13.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwAgCdASoQAAwAA4BaJbAC7AEPhD1SgGehMADMo0oMXuLhKW3Lc/u4hQ8xqQzbbbzukdee3M0c4KdCDxicmQfb9Ejzfljcf6ugLRidKh2jJH1SmeULlNyl6aublluAAAA="
    },
    {
      "src": "/inventory/1989-chevrolet-camaro-rs/14.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACwAgCdASoQAAwAA4BaJaACdH8AguCx5vIJyBHmtIAA/mtWTW2t/1JGVr+j93/8klVjDJEkd7FO7bQy99QdTm597Vgv1dvX6P0o7JTbVe9hLzjZwgSBOhcsMX85hobZBuOndP64Zw+FuAAA"
    },
    {
      "src": "/inventory/1989-chevrolet-camaro-rs/15.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAQCdASoQAAwAA4BaJYwCdAEfoxwEVpAAy0+MhO5raXK8ZdCKUUG/YOLZ5SmYVgrKj4mqLpG+O+5SowYW0vG/a1olFqQG1LzNyME1tkwWaSIcOSLyEHObpsZB4AAA"
    },
    {
      "src": "/inventory/1989-chevrolet-camaro-rs/16.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAADQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JZgBTAFwRBVT5WJHW5BAA8qFqmg0baeXek2LIMP7KP0cvbG+5nsCoiOiTDgUA8uEWotZO1/Y11jJLRaApcQTdrmSah8V4s7KBmaVBBfe9albudHuzAMEOeCTFM+sjpCo0P/NPyagzHMB+wXVpZBLI3YgshYtZ4X9/q7sp1jZir4Vw012U2d/d6KpcShIjh4GlB5usxAAAAA=="
    },
    {
      "src": "/inventory/1989-chevrolet-camaro-rs/17.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYgCdMoADOUJ97IlvRjxlscAA/qMU4gSfOgUNFFPBRw6J4rEqGnckPYYo8pR96RBcRs77APLYevu5px/6PWxU/qTHhSLi8CEhBUf7hiTN+Vcxt3sn36p6MwA2/hY7jbaw1U/F5gAAAA=="
    },
    {
      "src": "/inventory/1989-chevrolet-camaro-rs/18.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQAB8vSsb5dpBKwx2Cm8AAPuzt4j+LpvDeGpk9xdpQis1a/uJCcqDpD7/OqWSHnbBTMPykk5CL2xWNAXSfY4OzWO1DhaHTLnlBcic4HuvZlMfD09CNq+MpABDng+IvKXCfh1dvy3snmQQ181DqP4pH1Xy1daWIfxxfot9x0LrS0kEs9PqobAA"
    }
  ],
  "2002-ford-f-250-super-duty-xl": [
    {
      "src": "/inventory/2002-ford-f-250-super-duty-xl/01.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAwAA4BaJYwC7AEeg9ne14rYAP3jvpKcyGGhfLZtf0f20ci6a+9apWjA36Y2wUXcNYvpb6CeiUXY/MFOUWM+36UvZldSGoeBmwxBrfn4dEdLibaFw6AA"
    },
    {
      "src": "/inventory/2002-ford-f-250-super-duty-xl/02.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwAgCdASoQAAwAA4BaJYwC7AEed/vKo46kjAD9476TE2zHwVkqNx3z3nRtXy8Uiv4PJ0yfRtt9bMCCmdhKXyX94kIofKw+j33bILl7ko/iO5GmqLkYlVTAJX6vLEwA"
    },
    {
      "src": "/inventory/2002-ford-f-250-super-duty-xl/03.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAwAA4BaJZQCdAEVraWrnQQA/tUWsE6sUVxA3+q8DenEFXTVTQrXf1jnjhi3S80X4xbhb0urlMipHiuXs4U9GZ5Uq1AwIjADs0B7YAA="
    },
    {
      "src": "/inventory/2002-ford-f-250-super-duty-xl/04.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACQAgCdASoQAAwAA4BaJYwCsAYt92lSLsF8TuvCAADMJaRn97CPw2afHEXz1YnnGrZoZvwjXbSRuEv2v2kV7f1pf/8hWEU/2u4LlDnp0JOG0T9jtDiNASzhvA0qCdkAAAA="
    },
    {
      "src": "/inventory/2002-ford-f-250-super-duty-xl/05.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAwAA4BaJQBdgB4P8R+pewAAy0MYi1HP5QzrtLisA88Zus6IiSl0pxEFgrpzDv1yRHbmuoQWoRoKCF8Qfjz5mO0o01SzAAA="
    },
    {
      "src": "/inventory/2002-ford-f-250-super-duty-xl/06.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAwAA4BaJQAB8VIfdnzR/jgIAPa/c+95MF9/p38MC7CbaPQ/fFblONrEs6HkBvUnL2ElRK2R3O68TC84M8L8vVf1rb5ECHrlwfs1qSUL/bKJNkwG3cTA8AA="
    },
    {
      "src": "/inventory/2002-ford-f-250-super-duty-xl/07.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAQCdASoQAAwAA4BaJYwCdAEGUjHMAAD+uD68gdkKSDTC8EoWfAaiURqjhfpezzN1o8knjW79d4iAZ7R9x7SB18ANVnrnv96ZqOkhsdrcMLC25EOwhztaw1SMK+orvB5AAA=="
    },
    {
      "src": "/inventory/2002-ford-f-250-super-duty-xl/08.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwAgCdASoQAAwAA4BaJQBWAMVftbLtbPo9wAD+3IVSK+v96dpe/ED27HbJZd9F6wxCZvFRxP21XKIjsm0PhkolFA2alSkL61WOfaeuEe9WjycVY6jLeDBDifZAAA=="
    },
    {
      "src": "/inventory/2002-ford-f-250-super-duty-xl/09.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQAALw9OWKp2uSTz8oEAA/s7jDizjvBehTzxvBS63tblixukoqYfjhYGjMAgOyuaV/peXhV616UVQ/lXoAwgXQc95VV3jOBMtZb5UCjrSVFUwG1UjN33+6OgfDgAA"
    },
    {
      "src": "/inventory/2002-ford-f-250-super-duty-xl/10.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZQDCgYwI1bnCQrqFldzcgjdYAOJ+wETBScnIbxutbBahM4uGgVWUEqL2UtNQV/qUoLYGidoluCqNn2RfdCaSJzUEpXAkQ5QUL/LpyPmfz/qHji1jFqantIEbvkVOgp1u54JhgIJlJPpgzC9r12lQ3chbhkQN9JLYAA=="
    },
    {
      "src": "/inventory/2002-ford-f-250-super-duty-xl/11.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAQCdASoQAAwAA4BaJZQAAdPkMeMAAP3u9ia8njMt9iBBCVg0r68BfNLq+hw9Ufz8yXE5vaVXUWsWql3zPhUZLzRWiPbRH9rwPAAA"
    },
    {
      "src": "/inventory/2002-ford-f-250-super-duty-xl/12.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACQAQCdASoQAAwAA4BaJZQC/OBhGEAAzhlJCvp5eYoK7XJjEaW2Xa2AAXyQ9fl7PlGTnxznmRs2svp7O7d9iWGMyDzh+KEqu/z8cAAA"
    }
  ],
  "2014-audi-a7-3-0t-quattro-prestige": [
    {
      "src": "/inventory/2014-audi-a7-3-0t-quattro-prestige/01.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoQAAwAA4BaJYwAD45Pt45CnCdYAP6JG3/zh2/bIU3zoohDKywHFFtHMyuapaHnXhnCnq7u8N2NIANZUg7+m5zfQqcju6dDu/iG+vdb4KnepAeAAAA="
    },
    {
      "src": "/inventory/2014-audi-a7-3-0t-quattro-prestige/02.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAwAA4BaJZQC7AEVSnSUWAAA/us1drr6QkWrgOiplz3+0cAO3j04egcVU2Rl/LLKxGaVqRR+labYi8EFSJDXV9fcSZ+BLMhFbtHCYEAAAA=="
    },
    {
      "src": "/inventory/2014-audi-a7-3-0t-quattro-prestige/03.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoQAAwAA4BaJYwC7AEfBLs59EJQAPjjLG7L73kc7QK8rCk+JWVb5V0pC47swoekiwfYRvBl9rni9voAX4SuJ+p9J/lOAzwL3F0Kh6u9vQt5pXmCCAA="
    },
    {
      "src": "/inventory/2014-audi-a7-3-0t-quattro-prestige/04.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZQDCh2pQOhdmdSMHGc6onAD8j+RsaXnkfrcoM5+pmYcQbPKC1q4c6lbfVp9OIWT22+xsntbP5nrY6xvoBUKABwZzeOP6aJfuKEpujU18tGAl/R0DKX0JlAB8wP+S8GFACAAA"
    },
    {
      "src": "/inventory/2014-audi-a7-3-0t-quattro-prestige/05.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABQAgCdASoQAAwAA4BaJQBdgMWgtpNJah+5lwAA/tc56eh5zZeyuwAfJWkdXyf2t9f7UmzuA6wV5pDY6052DYPS21rfJjwVIaiDW9f2zGo7S/ZAPY8zX55h4AA="
    },
    {
      "src": "/inventory/2014-audi-a7-3-0t-quattro-prestige/06.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoQAAwAA4BaJQAB8h4uCVmtyBTgAP5oxO8FIvjBM9C/+72yDplX1AfdNwFnh5Bfihf9Zf5EJHydjKzvdpLDIRjxg/WwOt8Yp0T4B2XgmTf9SIPMIF21f7k9A8AAAA=="
    },
    {
      "src": "/inventory/2014-audi-a7-3-0t-quattro-prestige/07.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwAgCdASoQAAwAA4BaJQBdgMXh4HD5z/NnIAD+hAmhmAvHUO1MC4j/FJ7OmH71QyPCKc8r7iJ7K0OWE55TgD0xKW9f97nO7KgZL6yBnw65ORuzscAAAA=="
    },
    {
      "src": "/inventory/2014-audi-a7-3-0t-quattro-prestige/08.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JYwDE2CE7+UVxN0chZZAA/phck9RXwbkCFpD4oKIl9/sTSb/1AT1m353i0H5Baz3+H7Q6OZGPJqf9axYrrQzhipPaopoBgHjcd9SnsNdKiSG9bVFmlr+Q5AAAAA=="
    },
    {
      "src": "/inventory/2014-audi-a7-3-0t-quattro-prestige/09.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwAgCdASoQAAwAA4BaJZwAD43xeasrn8EC8ADyoY66NUYXiTFQbNEabMYdKr9CVLOa/BtTiH6WNbbsyL5w8jLNkIeodGx1utX2EmKMhAVz5utBMlBlxbgKgUQu7jCkRgAAAA=="
    },
    {
      "src": "/inventory/2014-audi-a7-3-0t-quattro-prestige/10.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAwAA4BaJZwAAxbR+PLYG2NAAPR2IRUTwQ18tWRnLxuC5/+azBe8f42A3JSJmtdHk54nwR46h6I/k3mXDsvLuQ4NCLa42QAAAA=="
    },
    {
      "src": "/inventory/2014-audi-a7-3-0t-quattro-prestige/11.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAwAA4BaJZwC7AD2N1tTpSAA8dbdnjDzaiagPv7oWjLxlYhaxgVHfXFuWKYgNMVD7+ApP6iTMV92vxRQL5ij8TF9x7AaAAA="
    },
    {
      "src": "/inventory/2014-audi-a7-3-0t-quattro-prestige/12.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwAgCdASoQAAwAA4BaJZwAD4/RAb5FwnejYADOM310j0grHDx28lvt6VEgrC9Vh7+tWozaJr1TOji0MuFiBCdevStDSsbrim2hCWegbW6halBrvPqAS/ZhkU8TPi6AAAA="
    }
  ],
  "2015-audi-q7-3-0t-quattro-premium-plus": [
    {
      "src": "/inventory/2015-audi-q7-3-0t-quattro-premium-plus/01.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoQAAwAA4BaJZQC7AYuG0jRAAD+g5vZd+K0a+YIww0TC/6xM6k19HRD8NcMksFv0yn+rHd8P8Y7ZB74/n21vqSMrVnE4oHApSUk+MvPd/EhgAAA"
    },
    {
      "src": "/inventory/2015-audi-q7-3-0t-quattro-premium-plus/02.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoQAAwAA4BaJZQCdAYvDjDGDL76AADeVn5EQg62vWyU7XqCyAO+Gp9dFsaq5H42o53A2uZyv9Uyh1QxaLbP3Y4X3Py5MKz6Sd0bwEo8Ah0VNelAAAA="
    },
    {
      "src": "/inventory/2015-audi-q7-3-0t-quattro-premium-plus/03.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwAgCdASoQAAwAA4BaJZwCdAEQUPovdKj4AAD2R9hAjJibdhlRnpbu668M169eGqzjbaZpjVsaTuTyT67dZZxlDUhbJpVjvQ95+hG/UGQ0Pk5DI5YGLiAH/pvsimcAAAA="
    },
    {
      "src": "/inventory/2015-audi-q7-3-0t-quattro-premium-plus/04.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAwAA4BaJYwCsAD1b/qrNsAAAPz3sQVZjQf/7SrgYSqORGIR8Det+ZPayLGU1HJ79FiQYeSIOPogicNM7chgmU/XTNOjdwyN4JJTBsCgFlAA"
    },
    {
      "src": "/inventory/2015-audi-q7-3-0t-quattro-premium-plus/05.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZQC7AB9Cxb9Iw37pJ0VAAAD2oo/nnMHC4xw2LKUY+fTQHGW5jAJ+puDKBntYn6GkHjoyTvNSkfem+DLe+UBvqUxE/fV6AebTkdN3XeQS0ndeay6lOYjDWltMwAAA"
    },
    {
      "src": "/inventory/2015-audi-q7-3-0t-quattro-premium-plus/06.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAwAA4BaJYwC7ADauN0IAADiBlIArzOi70Mhvj0d0oRWcRF6GX7kdBMToRK/Y4vtzfSEvYGd+Q+oPLCWbXTQh3azXZHtrdnBctO0tYOAAA=="
    },
    {
      "src": "/inventory/2015-audi-q7-3-0t-quattro-premium-plus/07.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAwAA4BaJZQC7AD1/FGArIIAAPzYs1I84IKDEV3X64Cy/h3CGeXNL3/Du9J2BYA7Bx4EJnhTcCzpAMaP1CwJIqXjfVCX2kze+jBN9eWJgAAA"
    },
    {
      "src": "/inventory/2015-audi-q7-3-0t-quattro-premium-plus/08.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYwCdABQ100WbuSeOuQkwAAD+mFxryg63k1+PyRXC+hKzc9x4D5ZUNC9apIbNSuWHp3PqxsOocxI9aNRxVisOEuQR6Ntf0GZ5Kdqzo3eDcTMRQCXeDbaD/5VtOOvo9XnFz0gxSA7dMAAA"
    },
    {
      "src": "/inventory/2015-audi-q7-3-0t-quattro-premium-plus/09.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZwAAYdos4WnKvQaKzOpuoADiEe8M/q2UiESP6JsO8x3624yvfQqPv568KjAxMNteHvNxIamdNa5dprn6WMY+lZIgZ1MSZEKdYC+HUEwVbA0T1Q+2Rmd3pfw3LJh9fRySPhAn+X8emYAA"
    },
    {
      "src": "/inventory/2015-audi-q7-3-0t-quattro-premium-plus/10.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAQAgCdASoQAAwAA4BaJZQAD5ArzZWoL2QAAPlOckPq6Y0fotWnm+4Xqr6wOlzs7z4AoIE3Ydpp1delYlB7qdaAjc/Vtt/Tbu3Mj0CcTDhOV8ds9LbCJf41pqqW/bc8V+GZrdtAAAA="
    },
    {
      "src": "/inventory/2015-audi-q7-3-0t-quattro-premium-plus/11.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABQAgCdASoQAAwAA4BaJYwCsAYvXlV5UQoevkAA/Gg8shr1enErm/DE67g6jdCrxQsisXq88Qcwgcyj5jqa3TFOMqHuzUJBhO7A4QOilva11KlRx4c/BwtoAAA="
    },
    {
      "src": "/inventory/2015-audi-q7-3-0t-quattro-premium-plus/12.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoQAAwAA4BaJZwAD42MD4bgCxAAAP4D3BvEGYpGFzB0hARiBlqcWtkLMX+RmkHA+W9XL1txdGRXb5ozC5oJI+9Po3ZB3Zo371zCt1277IOTM/FKinj3Mjz0SYEAAA=="
    },
    {
      "src": "/inventory/2015-audi-q7-3-0t-quattro-premium-plus/13.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAwAgCdASoQAAwAA4BaJZwAD4wO4zKgWQk0AAD+qhyI5sqm6/zKN/g2TZeYoEUsStXNKLXB1qtXsRTQ/qKPnKm31gT3k9CeDXkI1aI/9aHhW7E0ANYue9+lOa99Tkff/iZEXS8Hw0anKQSFAAA="
    },
    {
      "src": "/inventory/2015-audi-q7-3-0t-quattro-premium-plus/14.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwAgCdASoQAAwAA4BaJZQAD4uw3HyF7VsgAADh+ZeEHQsW7VCv47Qhut/vAtj/arnvjIlwo2Z0Df3+0d7CWCEDnD0rPCKWVHEi2N0qvk5vV2E2E50+817eV26J+T4TIgBZAAAA"
    },
    {
      "src": "/inventory/2015-audi-q7-3-0t-quattro-premium-plus/15.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAwAA4BaJQBOkCYjFOmEMJIAAP7a17qYirj2h9OYMsjscgZD1mZ21WawK85JoFp36H9mLDgYsUg4iMAWHHhqae22gNcPVAkaipybuhFJ3UFNhPdmTxcjgAA="
    }
  ],
  "2015-ram-promaster-1500-high-roof": [
    {
      "src": "/inventory/2015-ram-promaster-1500-high-roof/01.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAABQAgCdASoQAAwAA4BaJQBOgMWM7N3yzl57yAAA/on+wBZEf4X3sOokiTJVxcYJk9ydq4mkIz/jdQWHseL77uetUm0pWxorTMTzjv27F4e1OmxgnjcGDOXB673eA7tucWJyegrOKprQGZwAAAA="
    },
    {
      "src": "/inventory/2015-ram-promaster-1500-high-roof/02.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABwAgCdASoQAAwAA4BaJYwCsAYtB2w8RrMH7SAAAP7SsTW/FPWKhNuiDvj0/g8rF3nUe+LXap6UuCCcOAiSAWJCXh8zD2BCGRMO7ar6jgA/mrSKX0yzLwumYR2b7mysHXJoAA=="
    },
    {
      "src": "/inventory/2015-ram-promaster-1500-high-roof/03.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAQCdASoQAAwAA4BaJQBOgBUOyQCO4ADdduFPUkPPb/L8DGclTHHAi+NrE9Cvp5JqDAo++VsmtsyOHO/8rbp8Hhcyrx6xHcmqQMWqau6UMGilq1XFjbpey9W1vluYeNAAAA=="
    },
    {
      "src": "/inventory/2015-ram-promaster-1500-high-roof/04.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYgCdOUAKj6ZKO86OsIT0LZwAAP68Z0aJR55wfmVYTnQByhkmX5VxMlygNghHOwDknUno2dVI99e7R/GOI11YSgX2Inlb6cNEr5e40/1HzKaJPS7ZXqTIMEaNc9nq6Js1z/nMjuuSMHbPfOubSW2Jn8kjzQAA"
    },
    {
      "src": "/inventory/2015-ram-promaster-1500-high-roof/05.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOgBC07+OLS9kUHyeT0e96gAP36Qxs/mn7USv1oBjSS1dAglQSgnvFPLqazu0pMGMsAoVjJ83j/yy5awiV4KxO3TBq6xkdudRtzT2o+V4IJ1NEJIjlX8JA/AFN4BWn4dh7ktwAAAA=="
    },
    {
      "src": "/inventory/2015-ram-promaster-1500-high-roof/06.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBdgBH77ERDE3JsYwLckgADN2VvuOsADITbJtV3rjaGxsaLAGgYsSjeoseTqvvwwLZBnLrRq3vURiC5BW7OV4gE/+CeDwRw7sWUmFjnEnLsUDD+LZhEoB5O3xvASFfH+8jAFsQtepW8kgvEXJEmFHxGNwoVpkNC9zWoiAAA="
    },
    {
      "src": "/inventory/2015-ram-promaster-1500-high-roof/07.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAwAA4BaJQBOgCHN1IgwE4EAAP7rDngUNT2FVUaiET6r+ySezdUkl65ZY7zJqrilHrPogSEam4SjqBGu3oNcnKmGPM64JIfAAA=="
    },
    {
      "src": "/inventory/2015-ram-promaster-1500-high-roof/08.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAACwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBfnAX/A3V0c64PBWAD5C+0UNvZkCrI/HWcIzycGm7yRs5twZjh5YCCTdUjMTqW//Cc3AD7lx5GnwMJUv8r9RoZjFT0zn9KmQzLoIH9bMEuQDr4UTljhU9CUviR+XGwe8YrJgGfDS7gqkBA/bCcbguAIwAAA"
    },
    {
      "src": "/inventory/2015-ram-promaster-1500-high-roof/09.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAwAA4BaJZQCdAEXsvI4QQgAAP7ieEWC7c1Nh6JbgPqKpX+96JeINUUMox7toxP+I5MZuaHm4AGSAy5XkM4TV6p8y3AJUIdWC+/SMB+IztoBb3IyVAAA"
    }
  ],
  "2016-cadillac-escalade-esv-luxury-collection": [
    {
      "src": "/inventory/2016-cadillac-escalade-esv-luxury-collection/01.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAwAA4BaJYwAD4nRaM2TGdoAAOIGK3E58zZYR7NRtAggkzIfppZhoELDQJaXrugAXGe6aFu/9ppMuXuewJMVca5MwjH5Stg7YE8h0TABD2rafcTA8AAA"
    },
    {
      "src": "/inventory/2016-cadillac-escalade-esv-luxury-collection/02.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwAgCdASoQAAwAA4BaJZQCdAYxFttTMJ3kAAD+YWQ1urGv7X0nQFSBp2NgPzv6E8Q/ubG+bBI9DmokBmUxPxmfXYPjRsCBM0DYQPV6y8ik/KJam1Oj83COxKDIvwAA"
    },
    {
      "src": "/inventory/2016-cadillac-escalade-esv-luxury-collection/03.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYwC7ACLkNlaMjybGZ9dQAADyU8FY6hdZqJaEd+eBwq+qgkIEU85O42iF0ExBWlwYOvMLf8jVA9MwT/FfGRcyT9xXPnfKw/ySRK4cRzKF6m/kO+FPdaNdjP/0PnG2v0rlkQDqxKw/fAAA"
    },
    {
      "src": "/inventory/2016-cadillac-escalade-esv-luxury-collection/04.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAQCdASoQAAwAA4BaJYwCdAEKHb/gAADNda+9kymJjaK+SHcDVNeh0F/+V/tUE0T1CHDMjbG+czaz9N0Fjl3RsDb75613Hw7maHUChbGcyC+MKTYOO2xgAAA="
    },
    {
      "src": "/inventory/2016-cadillac-escalade-esv-luxury-collection/05.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoQAAwAA4BaJZQAD4wO6B4GQzAAAP51NS4H2//MxqPJueMn5ySboTr1YKIH8Q2GAfdhpziaIuRaQ8AAqYy+yeSmufcuR5zg4dAc1PiDTUyfScnvdFDHDKdGutCBunwA"
    },
    {
      "src": "/inventory/2016-cadillac-escalade-esv-luxury-collection/06.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYwCdACBz7w1/oIZRK5C2lgAA3Zvonrbe/J0mr8tJdq07XxS3SRLtC9rm2+XHuBLD3zuuJpYveKA0zj1B/96ERoInPWnPP20d5OeDd8Ewdcti7OMcg/l9JuRm43+8uyO03972hZ4AAA=="
    },
    {
      "src": "/inventory/2016-cadillac-escalade-esv-luxury-collection/07.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwAgCdASoQAAwAA4BaJZQCdAYwnwOdqEzIAAD+a1/6z+QxgMB2lWuI6dlYC1atj3dwfoQrLGzz+w9z3FtZPwNJ3YMlo81C3sSlSPdbCeMkb27YLh3S00qYs2ZCTgYAAAA="
    },
    {
      "src": "/inventory/2016-cadillac-escalade-esv-luxury-collection/08.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoQAAwAA4BaJZQCdAEQUN8DH70AAAD5QUJLK/8GMjW6a2u5kPr4S/DF1deJrmC8UL1VbO2gfKy2/gMyIN+uD+UvXBAZWmc6Zp9TmHNFgAA="
    },
    {
      "src": "/inventory/2016-cadillac-escalade-esv-luxury-collection/09.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZQDG9B+MCzXBEKiRRW412AD+5fgb5lclEMkZ3NMBC+ePJe621l3r1l1OH7YXaCIJCGCQYPi0bx/HX937GQ1g/fg1+WIoltAbL2OQdTho/McgHVygqpVX0JunRv1x6e9zTB+dxub2up6zY+ZY/Ft79glMTGfIE/n2cw0hb/nX3nFYB6pim2YDOG6sAA=="
    },
    {
      "src": "/inventory/2016-cadillac-escalade-esv-luxury-collection/10.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JZQATwAEZLmX/NNzRXWAA4CuOXgRZdEhpq3UMk3Ken94N/YxDAf6/jF7FJs6XfcoKcbrMT0/XLCEMzFfT1tTRCLpOvOZNLXHwxmkdg2GoV/WlJooP+LYICeinF0qmqO5kmpshtUSFwe4jWMBv2v8KkBLn+Xnk4AA="
    },
    {
      "src": "/inventory/2016-cadillac-escalade-esv-luxury-collection/11.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JZQAASpLx2iLC3YqzGyLAAP66DRIv79EI/CiVanH3IHAUnbox2fzkncJQipqpcB+WHt79ZRGsyJOACU7estFEq5ffXic3/iu5RYuWRO1RKoRceWRVxaW9KmKUU4i9CAFHwhBrcSg6AAAA"
    },
    {
      "src": "/inventory/2016-cadillac-escalade-esv-luxury-collection/12.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZwC+aMgCFHI/+pCAmzD0wADEKF2dSpbyE/xwdrF4qNYjMqW5nINLgAqILU3dFVfAzAkhYO4pjN1qTdaatTqJb2R0GLQ6gXrQvYSkLbqbt0u34wm1SjXJQlv7xbnDetviPp2W7ZZHWo12fEEQEbB2AAA="
    },
    {
      "src": "/inventory/2016-cadillac-escalade-esv-luxury-collection/13.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JZQCdABuJTGV9KSfX56wAAPd1YuObgZEFDSQ5TJDi3wDMtwrl7i2o5AqTdsZytdQ0iiqWIJWWgnDzrfNenlUY9Nr8z2e9w/Nj6TXscU3GTNIawae915yZ1gbZxDMaryt36aKpwO4W7XPWgf+q8Dt/XTSTgeJMN1u8ewd5VsQAAA=="
    },
    {
      "src": "/inventory/2016-cadillac-escalade-esv-luxury-collection/14.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZQDG9B6XR2IsZnVo6ckVgAD7neT4kLKPGCEiSpwykl7l1bFjRtdcU3L8H7KZMmDMi82a6EpVzZpD/a7DiSlG8AubiHh13ztZ3ZjyhPBvtdIJhkD7rr26SHN+sCEtQs2ECMhq7kl2Ci8491zp0nJx46CuPBmPjSNvvtpxRAGAAA=="
    },
    {
      "src": "/inventory/2016-cadillac-escalade-esv-luxury-collection/15.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACQAQCdASoQAAwAA4BaJZQAAUjlzfgA/QDDVWcTtP80Sz6QMVhmdkqJkm2egWhbIsgfscEmRmYzxCSjT5+Bvy/lHNm9iNyXAmWpxs36hCaoVPXL1Dpno2AA"
    }
  ],
  "2016-ford-f-350-super-duty": [
    {
      "src": "/inventory/2016-ford-f-350-super-duty/01.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoQAAwAA4BaJaACdADMJdy8e6AAAPZvh7N+faJ6W1WiZlIR8x2LKE5GbK+HbzY9Cjx041PY1xlw0f2QNcjwDFnz51I9R263noATnykNA3rQMpM61nBEKGeWePkgAA=="
    },
    {
      "src": "/inventory/2016-ford-f-350-super-duty/02.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABQAgCdASoQAAwAA4BaJZgCdGuAAt1I6TGYc5gA9Fseo5a1tzl7XXO1cMzX+yaqBOEBQMiFRNtCL1IDXFsMrmsVFjLwG9wsSrLSaQQVgpVrrii8xxPum5w92ov4n+AA"
    },
    {
      "src": "/inventory/2016-ford-f-350-super-duty/03.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAwAA4BaJagCdGuAAsJxwVuAAN+MtkmDErleBwYpO5B5ub+Z3yyFsB2wHqBg+6qmKWuBqBxbQJqrKpImJ7XXFLaOUFVmvl63YAAA"
    },
    {
      "src": "/inventory/2016-ford-f-350-super-duty/04.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JZwAAW+L5JcscR2sHB/AAy09+dbVskBl6APWQS05lJPTJv2OEOAlLyPObBVDEQIvFp+Wx4xgTuDeBWtertP7tPpvRlngw5rp0ULX2+BUEuQf6jIouPzmP9Rj/s3GTGK/LFMT9RFA548A9m5Z2YldAAAA="
    },
    {
      "src": "/inventory/2016-ford-f-350-super-duty/05.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAwAgCdASoQAAwAA4BaJYwCdAYuvawh4fZEAAD+cp/EL+Kou3U88a+cPCQgGeKXogkfxTMaryWGUEDiE3D31KhGEFmjrWl0cIrVq3vmlKUAAA=="
    },
    {
      "src": "/inventory/2016-ford-f-350-super-duty/06.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoQAAwAA4BaJZQC7AEO//MLAQAAAP5stkLmYJjV5znIbPHGXasPUt3KlUdnpHP9DmBpAjunPow3rOoIo8Ux3NKn1FKhTh+cr7Y0cf7h8arHk5Y4wAA="
    },
    {
      "src": "/inventory/2016-ford-f-350-super-duty/07.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwAgCdASoQAAwAA4BaJQBdgMXDqS/eLD6m3AD+4lS09f1LV210OSneW0ts/UQ8Y+TWgNCd1up3m8ZcFm+ChTAJkEFS/6EjFmYvoGXDARy3cC3N4jjrUKqLVll6sqtL1+awAAAA"
    },
    {
      "src": "/inventory/2016-ford-f-350-super-duty/08.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABQAgCdASoQAAwAA4BaJZACdAYtBq3KgAA+F8AA/uFfzD/3VN65Tq6TAdAEyCZRHqXFzbTKAXrsuhqBQ2MnpN3UG6xx7er7f3P8q/ohk/C63uZzN6PBSOSn82F4ww3dwi4rsAAA"
    },
    {
      "src": "/inventory/2016-ford-f-350-super-duty/09.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZAC7AB0irreR99kyrjqLAADxscZvoNjaqbrTV8uCn4SAqUz6hoqZgU9dGELjwprCsPuGq9dZwF+HOuJ9Prtp67eXwbL9keNk69Bc8BF/4pAAChuzVrdO+KeGFekRNijTYx1fDKYHhzsAAAA="
    },
    {
      "src": "/inventory/2016-ford-f-350-super-duty/10.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAQAgCdASoQAAwAA4BaJYgCdADcSKeRlb2AAP3wJhauhHvA0uTe8BWJqDvZvYSiWgO/mYC2gKKOHQnTuqtOsu0KJHG2C87UxrYtOB5gdy1aRiVmsNQh1jDei9iJKb4kX2XJGL4AAAA="
    },
    {
      "src": "/inventory/2016-ford-f-350-super-duty/11.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoQAAwAA4BaJbACdAEQW9ioCqvwAAD94ZUPbQY3mUsVKHYLgWfva7uycGrxCDHrv+QyJoEO/qcLaJgV76774WahMpfKmlpfxXHfD8X3yPyhMAAA"
    },
    {
      "src": "/inventory/2016-ford-f-350-super-duty/12.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAQCdASoQAAwAA4BaJaACdACQv+1aYADMTGGS6iUSXGcnwIE1Wi+vmql3J9I9StyvQ0c6OWaTUzN2u+8fxieYMd+/Kv6s8SQMGvv2yujz45trrvmEUkvfie1S1yM0NRIAAA=="
    },
    {
      "src": "/inventory/2016-ford-f-350-super-duty/13.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwAgCdASoQAAwAA4BaJYgCdGuAAodILxW5gAD+qffAel3+3Z5t9nACw6+S8BjVFlDcbhMHq9JM3rI99oei67NT1aZKUGD+5FoGPExOElAKXYn/kfC8ua5xVrXbQtagAAA="
    },
    {
      "src": "/inventory/2016-ford-f-350-super-duty/14.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQAgCdASoQAAwAA4BaJbACdGuAAop+0lLsOPAA8dWBO1Quc2n5OBjFtXWbTli3v+VxTyQn0/YcB3UwG+78LDZwiwpaGzuPFILlkE46YldnBxBX5wiVZr5dsAAAAA=="
    }
  ],
  "2017-chrysler-pacifica-touring": [
    {
      "src": "/inventory/2017-chrysler-pacifica-touring/01.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAwAA4BaJYwCw7Yte/dVkAAA/VLmENRCPQuAUT1bX/yFIvOyJI+ieZ3qZtHDilf+FsMj8prKJjL0js2z2G1Iqa/G68W80EzqlLPMcAA="
    },
    {
      "src": "/inventory/2017-chrysler-pacifica-touring/02.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwAgCdASoQAAwAA4BaJZQAD5Mu1JVna/0AQAD3399kMPAFUvhgwMv2AMeqH4NS46F/PME9l/BbMBX9ymEXUBDhmrIVhoDR4wj7rLEAgCOirGI856UoQTXFhUexAF7IAAA="
    },
    {
      "src": "/inventory/2017-chrysler-pacifica-touring/03.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZQC7AB0kbOKoDqSn5oDawAD4MFEVJPWhN4dpMva8EpxnU2fQvC/uN9aFPcKN1S4d03+Kcn19644pUjVNsD3XBQAKyPBp+ra637K4exG3/sF7kB0T5hHzULMKGTGFfpwAAA=="
    },
    {
      "src": "/inventory/2017-chrysler-pacifica-touring/04.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JZQDCgCK2f8SH3Vnewh9IAP6+hAbOUVMhJJaH31aJvDrDjUgea2bbov/iWrPmPX9rVc+X9UeBgZUj2gc9v6Vx53nvsbt7o/4JF5dtDam0+JvOpLz2NLcidGEqHI5YEF6X+SiLFZNyBl7dQekkuhfhR76qzv77tg1cAQbd1s+ABIAA"
    },
    {
      "src": "/inventory/2017-chrysler-pacifica-touring/05.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwAgCdASoQAAwAA4BaJZwAD49vqQzzKdtQAAD2dh34+F/4u0xifPoJEy8V7tK44C57i+0/lGfj3MICFgyFTy+e7sLOpz/7EbpfzAvcp3KrK8tV+7KcgcKr0WJ25dIAAAA="
    },
    {
      "src": "/inventory/2017-chrysler-pacifica-touring/06.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JYwCdABRj29b6/jj9vxgAAP5VJAnW2sz2lK1Nj0f3SjvasCPtu9O0+ng2eLvwIk3HrSY+iK/BLSTqRyizFKvOxlGXwHMJMLL+miaCax/NTrMrcrHbx1/hS/8KX62rQ6QXy92BTa4htwvMYWL+kqpXyV2c2S4WZKoAAA=="
    },
    {
      "src": "/inventory/2017-chrysler-pacifica-touring/07.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOnKAAcXzytpRkAAP4g+Z+8CuHDgvYi3DDBsCZjv99RjOkeNNhVpkhwqEsBQBmvDDqP+Zbm/SE6GNStwwCiOhJEPFNKlAAAAA=="
    },
    {
      "src": "/inventory/2017-chrysler-pacifica-touring/08.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoQAAwAA4BaJQBOgCFsnBwWrtSwAP5gLRV5zclpKhV+o8umMUq3wH787E75STpCki0L+hWUZb2SAjbCLhDhSJQrmrt0PbJp2RrWCTWkCwfUsRUvt7RZZvrQyhTMAA=="
    },
    {
      "src": "/inventory/2017-chrysler-pacifica-touring/09.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACQAgCdASoQAAwAA4BaJZQCdIExgrjBTm+7LUSYAAD5QoWZzxH7y5H+EPALLm3HHhMIJx5eyMlJcwqoRQAJJa7SbUs+J1QKtMg5Par4XJ2BUg8L1P0qGdBw/VlE0GUuhF3T96bCvg2uuq0AAAA="
    },
    {
      "src": "/inventory/2017-chrysler-pacifica-touring/10.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOkCYg6FOJU9p2fG2ihwADLSxaUJdPHOu9EUsejUMsVDkE/NbNvqJCsr64XOa/dmh8XbPCxqvxPvYnbFS3oZxYJwhw2Msx0aFx0rlay7SJx4aCewI9l5uTIOsEQCY2MhQAA"
    },
    {
      "src": "/inventory/2017-chrysler-pacifica-touring/11.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAwAgCdASoQAAwAA4BaJYwCdAYubWjLBoOugAD+o39/RxkNw5EoJWWv41wYWVBU6xSW0U1RE5VViDy2CggBJxwoIhm9wHq5VGvkTZQxjEaEzWK3eY8pzULn7bOjOfxs7PfXAOKRAAA="
    },
    {
      "src": "/inventory/2017-chrysler-pacifica-touring/12.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACwAQCdASoQAAwAA4BaJQBOgBuQEl/wAMq2ksEiPH/W1h2WlTUYUlwWlGLwajoDChvyhkN/lSFBR4L5io7dCfBbzgUPUz0RhdCYj/bnNIrXEYAPHERiAA=="
    }
  ],
  "2018-chrysler-pacifica-lx": [
    {
      "src": "/inventory/2018-chrysler-pacifica-lx/01.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABQAgCdASoQAAwAA4BaJbACdAYv/zDyReaSgOAA/OMpkd34C62eF/HO4G/JMcEB5gFezzPuwUur7FuxBHAuuVFZBCF8yQS2Hd3MR6ltysilSo0UMwYNCb4nQWDuCZYJqw2P3dWAAAA="
    },
    {
      "src": "/inventory/2018-chrysler-pacifica-lx/02.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdMoABXqbIAoDVZgAAsXcnlmoO8yo3gtsf/WoDqbAuTlsTInMdeF1GdSFMPgyGkciJZWFhQKCHcoCpM5bO0yfeX6HfB4/2lVqP93uXQH1rL4qrMUyaOP6aFM8AdRdTVuJgWUrkkbxXvTLYCqOeAAA="
    },
    {
      "src": "/inventory/2018-chrysler-pacifica-lx/03.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABQAgCdASoQAAwAA4BaJbACdAYuHvueibuvtIAA/rxxu3T0R3gJeIOKMtSn0RlCTz731wE2sZbkMy8PQ5CY6BeVKL6c8q1V0ZhIw3qf/GYxf/h+uXlRc+N7fQ+cJADYAAA="
    },
    {
      "src": "/inventory/2018-chrysler-pacifica-lx/04.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoQAAwAA4BaJZgCdADxL1Cu6a4AAPkEQYzKjczpEu0sJ7kXLWSxKB6xL15Vgte4KIR7KhgiXnDFYzJ4yWjw16QDp48AA5Eop5cMzv3OmKkAsViNjeJukIyQHN47AAAA"
    },
    {
      "src": "/inventory/2018-chrysler-pacifica-lx/05.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAwAA4BaJQBOgCIZZ+rc4QAA/qbOSrQo9T2Jw5Ao5wVmgs9CKKRoPl6f0LDRJfQV6fBkHvLa7BMQ9iGSHclXiqu2kWlj6WlT19wOKzAAAA=="
    },
    {
      "src": "/inventory/2018-chrysler-pacifica-lx/06.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbACdLpWAYQAvSAG5kK+8MQAA8YkKSrqDeFBff04CYlFXUdQc13TlpAEGSVYohlzKeCmLGOGtEeTeWRgdzqZ6ACcG6TXYFtNEW2qMqAI8nWwtERHvpc1pTU+ouaxAoLsAAA=="
    },
    {
      "src": "/inventory/2018-chrysler-pacifica-lx/07.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoQAAwAA4BaJbACdAEQ/W6bMpAAAP7oTw11Z118/IBlvi5+IATlpCnoZNMjfgdt97HyWlg9ByOkxTJaE3OyJBAceZ7OYCJzTtt0sFaJ/s4Q2CfMueW1BfPXA0AAAA=="
    },
    {
      "src": "/inventory/2018-chrysler-pacifica-lx/08.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABQAgCdASoQAAwAA4BaJbACdAYvD2hefb+0UAAA/uGrrY1kGeE6ydOmAW9te/c5kJtIK8pflM4GJ8puwX+EoOx6FUJG6wrfAldmAvVpciaD8y0h8sO4xKrzbHqOst6OQTLAIY5oq/xIYAAA"
    },
    {
      "src": "/inventory/2018-chrysler-pacifica-lx/09.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADQAQCdASoQAAwAA4BaJQBdgBI2P8uAAAD+W3ZJGmIqJu1Qfppl08yzY7eb1gU3TaNxir5Xl5zGIsdElC/eaFsSA6/7keNYVtxH1Qg7/9FmeQcKvkXYTQAOQl7QA9coAAA="
    },
    {
      "src": "/inventory/2018-chrysler-pacifica-lx/10.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAwAgCdASoQAAwAA4BaJYwCsAYt9tL9cfgOAAD+m4WYSWppCjw+MSmU9drB2zcZrDlZcEfkWB2BupSkt3dJMqxt3lYxsIsIMqctFi578l3uwBPIcPOgVuZf11V2fzIYdEe6qB1ggAA="
    },
    {
      "src": "/inventory/2018-chrysler-pacifica-lx/11.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAACwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBYdsW0X/NIpyXbXAADOGAYTIkaadsfkOEbgZOIyjN+tC1mMD3AxlK2vPDaiw5YtBYuDVS9mctREFQULe9GBW1kXXf0Jpf3P4WN/rfGSpFclgr3knrVyFwysDH/1v0g0RrKg2UD+npPdMDoSES1UA9/IAA=="
    },
    {
      "src": "/inventory/2018-chrysler-pacifica-lx/12.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAQCdASoQAAwAA4BaJQAB8n211qpgAP7VFnfHMre0GLKSl51feexvEPpEqwC7n2l7xhAArDD7SEUoM/zBUMiEZix/PoBUu3XYtbQXQA56X5MNrdEXc0FwIasUw/AA"
    },
    {
      "src": "/inventory/2018-chrysler-pacifica-lx/13.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAwAA4BaJZwAD5CLes/8XlAA/pG+WuxwsKqonEtcF71TysbsVk1quWwOe44TQNMFH+PMNq4LBm5YOvyHENp6PLSz0b+hL4v9bB9EvcQ4AA=="
    }
  ],
  "2019-ford-f-250-super-duty-xl": [
    {
      "src": "/inventory/2019-ford-f-250-super-duty-xl/01.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAwAA4BaJYwCdADp0/Uk/JAAAP62x5KDHh7qLl3P0l4A16JsdK6B1y3H0BUtlhvYnX/sR++c+RQuzS/b+LTpgq3zRr/oTNS4Z/6z7O/+2zQFdggAAA=="
    },
    {
      "src": "/inventory/2019-ford-f-250-super-duty-xl/02.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQAgCdASoQAAwAA4BaJZwAD4zMitr3akwAAP6tQ+sgAL06UvlomGFiqK/iNDF6Mt5WK09GJaPAX54d5fN9Myqi+/kG9sooPmXbKkeptfiPGHgDx1WiqGddursHII6ahaxBb3sjpHAAAA=="
    },
    {
      "src": "/inventory/2019-ford-f-250-super-duty-xl/03.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABQAgCdASoQAAwAA4BaJYwC7AYstnan2/4UVVAA/sptY3VIt2A68Pt8KhdLybuwru6khGsi8RxzfX8B95BEDqkhFVo2qY+Vbv4NTkLc0v1sBJNSNW+d2CqwdePbYaUZfItpEI6DYAA="
    },
    {
      "src": "/inventory/2019-ford-f-250-super-duty-xl/04.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoQAAwAA4BaJYwC7ADwTjnwAAD+rUcG9em617p78HhfzSjkvd0FdbyTC+/ppi7qedMcIGwFoFxMZQZv1SMprGO2phZ5NzY/2Eow5AyPqoJC/mAA"
    },
    {
      "src": "/inventory/2019-ford-f-250-super-duty-xl/05.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAwAA4BaJZwAAq8Nb0sY3QAA/rDv2NDy/kkgeZG/5DQ2U3yha5PLj17j1ZCjtW54xJ++zXDU/xf7Xs52JmD3VZ23UKQdSIS1SZkglp3Ylo1ZKTQAAA=="
    },
    {
      "src": "/inventory/2019-ford-f-250-super-duty-xl/06.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwAgCdASoQAAwAA4BaJZwAD49vNJoEkxSsAADxF6SOGICD4Og5xH5cMPnK+hvxZ1vHroPfllSmY5U8yfMNl8EVXDn/NmpUdQDLfotvdIHYMp+Pqo1+2Dlzp8tvraLX3gqeLoAA"
    },
    {
      "src": "/inventory/2019-ford-f-250-super-duty-xl/07.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoQAAwAA4BaJZQC7AYulzAgf7wLdwAA/ubF/kW8VnWY/21zOK+9kQAVe+HV/Vr5pI3UyiKKJLnDQ5pDuazq6GXUaaPosNrJvDEvnNlHKaOLMCRPBy7bPJCNmjgAAA=="
    },
    {
      "src": "/inventory/2019-ford-f-250-super-duty-xl/08.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZQCdBagBTjVkJUA3V0FEWAD+50CXciQyLd0BJWRB7iwkO66/7BJHzh8sqja4sM6r3Eepu96GoExPqjMXGKUaz8YkZY7a3hOhinI2BNIAdTvxn4sS6njtFOpUYg2VtTt9WAAA"
    },
    {
      "src": "/inventory/2019-ford-f-250-super-duty-xl/09.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABQAgCdASoQAAwAA4BaJZQCsAYu5WUt7oCdvQAA/b8TU+QH1PYtqDfhUcr3cE09crK6syIQ5Wizp7h3n0NS/6Lz7hgwpspiLeki4l1wpcT2Iu7kCuglHYfOIK+7jRZ16J/MAAAA"
    },
    {
      "src": "/inventory/2019-ford-f-250-super-duty-xl/10.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAwAA4BaJYwCdAEPBop6nbWAAP7q5LlZxXWCNd9UiDBDDzA9dp1H8jP1frqzk/z6Ds4jm+IYD4zQcFgcuSxogxaHI5H1aArsEAAA"
    },
    {
      "src": "/inventory/2019-ford-f-250-super-duty-xl/11.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZQCdACLKOrfhukj/8r1pgAD+52gkUFxErHAKsDQ4ywqNuOIHo1rP1CW1TO8wXdTFANjrmKj352vUHkJYL8Ckf2APzLYDpfenrbjh04xzdkofWEWOZ3/NpDsbwAAA"
    }
  ],
  "2020-dodge-grand-caravan-sxt": [
    {
      "src": "/inventory/2020-dodge-grand-caravan-sxt/01.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAQCdASoQAAwAA4BaJYwAAmfNflm5+AD+rXEehqoX3M7A+sggr4UJuIlGezhB5OPWLvzyFs1rIWA1LT9hQkGssKRHhlKK6h7bwg3MPCAvRNj6nsqncTA8AAA="
    },
    {
      "src": "/inventory/2020-dodge-grand-caravan-sxt/02.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZQCw7Bbb+X8ssgUx6TXaIAAA/ugzEcG5jQJB3UhHptXi/sC8Y0Z5wNNQ15l2tEl5ST36gYa53QtudlfLT9OIDKM0rZX6jFwqNXfIdPlImX+NTFMBQA6pQwvWNfuWvWcGGn9eNiibT2fytfTBDN25CVgkN78KEAA="
    },
    {
      "src": "/inventory/2020-dodge-grand-caravan-sxt/03.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABQAgCdASoQAAwAA4BaJYwAD4WwiCv4kY/8qgAA+XB63e2QDUP96R8Oe3PTI3XeYg/GG/e4uTHg9NK9KKAEXsW8efj6nIqfd9v83HzE+YJoirk1P/ux7ay93/Zi9SA8AAA="
    },
    {
      "src": "/inventory/2020-dodge-grand-caravan-sxt/04.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZQC7AYuG1XtA963RNlPRGZgA/uxH4qnI+WAtKzj0khb5AeLHra4tNrhyPe7Vcl6/tR/NMKntdILK7ipwxMvOysFtFo06NJGd0NDLnWk6WsRRuBL4IuqoZzfs4YOVLR7lMjrb7btBeDIWTHSLic3Yg/IPdbiMi7lJqOFNnaAAAA=="
    },
    {
      "src": "/inventory/2020-dodge-grand-caravan-sxt/05.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZQC+SCG77XGJqKMONNChTAD+7o+szrDzz/VgOjyB59QL0L5Z/1OvXFhVe1O1kM0/PIiWENWCQPu0Nz4KKnPvJZ7Up64RDT/G+V7WeE/O0rXmQ6NPNwvT4gfhZejdKKvYLCpa7VOhdxYHFgAAAA=="
    },
    {
      "src": "/inventory/2020-dodge-grand-caravan-sxt/06.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZQDLLBmBYNJRqhL5TmWizAAA++xuhVS1xl/rxNoteyVrRwjfDo8qXO3fwWHu65C1dRu15oPJ0pGPpvGrJ2TVHFyX7XJ9zBn8GXYp5HGszJC+pMCqY4S/fgtTPDlycWWt0CREJipmgx2f+UeobN0lu+19WxEwXfOru1DjTuVBhSrgOfAAAA=="
    },
    {
      "src": "/inventory/2020-dodge-grand-caravan-sxt/07.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZwDE2CBr9w78C8OwladBcboAAP628VYR4w+Bftp2NXKpfe+6wOkQ3QFI+bRASdj6Uje9kOq1A8EidMeecEkk69sHPHvwn025eVkvPZEsirzsyTnujg6/rA/KVsJCAAA="
    },
    {
      "src": "/inventory/2020-dodge-grand-caravan-sxt/08.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABwAgCdASoQAAwAA4BaJZwAD4owjldL/rDH8s3wAPZ1PFydQ3oekAGgruex3GQWC/OC5j6I/sD6C9S+06QIvccpOvPqOeSn77qzdeDSevgoeygueB/m21QyK8qd3ESahDEOd+1Ac/2tfiQA"
    }
  ],
  "2021-ford-bronco-sport-outer-banks": [
    {
      "src": "/inventory/2021-ford-bronco-sport-outer-banks/01.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQAgCdASoQAAwAA4BaJYwC7AEXuPL7kT3w0QAA/cNj8R0fHlxeD3sL0ZENJWMNVZe4OZNWHuFfq1+tGU6JF4Gf33MtL7ayMS8m37nhMTFoAKHd1mrxgqZHJHBIAA=="
    },
    {
      "src": "/inventory/2021-ford-bronco-sport-outer-banks/02.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JbAC7AB09YK3/IUc+eRhCIADyY6Q9ljpwreq+nxees14fsWYP565ghD1WxxuzmCZVzF6cs2Urs7ow+Zh9YoEYK6AV+l/ztUcmc0RYXR+R9MdbQmsUmLP2rpZ12TLJM4p4NuMYftdkNzUzojcqjT7AJL1xc/DJIFrAAA=="
    },
    {
      "src": "/inventory/2021-ford-bronco-sport-outer-banks/03.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoQAAwAA4BaJZQAD46vseTxc+VwAPhj6beIyJPhJ5ZVJDvqfRf6EAzkbRGzUW/wv/ucnso86UlpTq//8Le3Shz+kR5lFIwSnVR58pRug9a9Zxa9cjZRpQm6RB4nLAAA"
    },
    {
      "src": "/inventory/2021-ford-bronco-sport-outer-banks/04.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAwAA4BaJYgC7AEJy8ow018AAP60LtgY8vfw14A+lqwuDQ377pVqTV+4fMB0B/dHcdEmd3ssFNXm3jN+AbLVdGWqDX9U/ctAAA=="
    },
    {
      "src": "/inventory/2021-ford-bronco-sport-outer-banks/05.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZAC7AB9SAStaSI6xBLvpRAD+6/92+CYuyBaQX8pD2DzBsXo8spcBesZxQyesP9nW+c8qNOZvG5sBKudFS9chSR6rSCYpjlBu/I1dysElxEgfCA5jpcpoqAzN28CXcS9AfHocGQnOQAAA"
    },
    {
      "src": "/inventory/2021-ford-bronco-sport-outer-banks/06.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAwAA4BaJQBOgMXc39GB1wNgAP62xxap8+b0XWg6H9HS7CnG/+2FWDsCCL9+x8nvCjyCiHjtXuNSh4FlEq1OL7EPomwHhgK5p1mSLON+rCHdV8jko/1mAAA="
    },
    {
      "src": "/inventory/2021-ford-bronco-sport-outer-banks/07.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABQAgCdASoQAAwAA4BaJYwCdAYtp2VTU1/XDgAA/LT5SQvCAnDZFqI07M6p44TrmWVg86U+0M2AAzsNAX2CpKWyhRRaRqS9oCAmCdRGKIpUJbVC8exu08gsiQI+IB76AAA="
    }
  ],
  "2023-toyota-tundra-sr5": [
    {
      "src": "/inventory/2023-toyota-tundra-sr5/01.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAwAA4BaJYwCdAYt9LkDqqsAAP7b45Qn5AVO9vJqOsWuPMUWd6vAvUnf3oLexmebd2qU9CBBqPz3lnL/Bao/FV9aPk/GaAA="
    },
    {
      "src": "/inventory/2023-toyota-tundra-sr5/02.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAwAA4BaJQBOgCFsmt9NVgAA/rYfp5WQASCJuw5usAeOHKYSxYjENmnDGvzbvd/kPlSPC9M8oXS4hH56rcMtC6bsuaBuwIYdb+4+9/LDuqQA"
    },
    {
      "src": "/inventory/2023-toyota-tundra-sr5/03.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JYwC06Bwnl3KxkNI27AYmAPsYNkOXX2bKQhXl3lkCHf9ywa2Kow7XBNe1feK9jw/jAIG7wQEwvsBH4p11Pz+IazqSB5+BUuFzutUvt01Jy9yYzxumDrcKK3Ur+BsStstFGgAA"
    },
    {
      "src": "/inventory/2023-toyota-tundra-sr5/04.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAwAgCdASoQAAwAA4BaJQBdgCPTeaO2U4rfBAD+ps2wSNIDJb6sB7lSe+sRvSnGibY/8rJg4cNxRv8N0FggbB+b96yDJpjZfEsKAAAA"
    },
    {
      "src": "/inventory/2023-toyota-tundra-sr5/05.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JYwC06CFssPDZVZQ9yhAAAP7x21URDcqp8KlJmHadHMaD799xOeglc4BFiC9bqKgEOUPWTlWgzqgj6B6kkN7KwIzIpSnZZbvhS/OdEN7x6e+5868Ho6O4UCUnbSuAWol10AAA"
    },
    {
      "src": "/inventory/2023-toyota-tundra-sr5/06.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAQBACdASoQABUAPu1iqU2ppaQiMAgBMB2JZwDLLB6yHPlLqiBb4842gAD+5Op6J10AMKf+xIt1ZwlkFqUhc7yQJqfhSljh6ria5qQGKZv3WN7W4tkjjWx4fKzqvXtMSZywlgDlYeUoEAAA"
    },
    {
      "src": "/inventory/2023-toyota-tundra-sr5/07.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAACwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JZwAALbm01CyD8w/UwAD8ojOAaFLMyWtT2mswNEu2rDK0vc4fJGpFfceV2c41WLGlbo04pY6uK8MQjNF1xMS6F8PJC0y6z5UbEpw0YtscLuMZ9xbx6dKF5ea1x1vsevjwrQAA"
    },
    {
      "src": "/inventory/2023-toyota-tundra-sr5/08.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACQAQCdASoQAAwAA4BaJYwAATL2wAAA/AH4ZZRIMV7DXzLTAADrKmUTFFneY9Lz7RybiCWatTfVB1zgCYYHP5ACP1vUInfffBJI9trU9sO4WF3EwPAAAA=="
    },
    {
      "src": "/inventory/2023-toyota-tundra-sr5/09.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQA7gvgABcylJDhDXQfJfQAD94d7SRnmfeE0sLBRbT7nO0zOakINVat0WKVsjIxS+LbSoZlxS2Iwut+Xlc4m3FSADHmWmujplit6toM2fLv7ZjkMyMAAA"
    },
    {
      "src": "/inventory/2023-toyota-tundra-sr5/10.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZQDE2ywToQm+VAe6Yznw61jiwAD329qG4SiuXZPGC7ihOICTOqHnsW7oqrz7mh0QmwA+OtrNpvpqUaADsolnleXRtfR8B0vi5XxSW4owxdKawA6Bh8kF4XAmF1rd8BFlIpu0lLxG47xfOQKpL6hM3wK342ED0RNlRAAA"
    },
    {
      "src": "/inventory/2023-toyota-tundra-sr5/11.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAQCdASoQAAwAA4BaJZwAAujGmgV1gAD+Zt+tbR30RPmtTDyqsdsmi70CkBXPpSJN0A5FoAMk2jSfxzmTB4MLSfXlOevLc4bAg+X9G3BAYXpkBJF8afvl8UoHwAAA"
    },
    {
      "src": "/inventory/2023-toyota-tundra-sr5/12.webp",
      "width": 600,
      "height": 800,
      "blur": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQAALU7Oq3jRZ0K76Lk79wAD44qwbQLzsmgO96xn81lTuJLWTJJcGveIkULRdpT1ebc875RjvB/8LdhWdZPyO2/4bsW+qzV6RlW0WuZi2bVgvp01INVOYexph5SjM1j9CvHjYIIinsHjXgLYcPV2Ou05vJY/PAAA="
    },
    {
      "src": "/inventory/2023-toyota-tundra-sr5/13.webp",
      "width": 800,
      "height": 600,
      "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAwAA4BaJZAAAuf6tmTCYADh/CLA5ydqs+ElMqJMCUiey1aCJC7q6Ge9Gw7wNWUJXpXd8oa5GsdVq+mXlaipua/wOXaqXvoIAAAA"
    }
  ]
};
