/** Shared inventory types. See content/inventory.ts for how to add a vehicle. */

export type Body = "truck" | "suv" | "car" | "van";
export type VehicleStatus = "available" | "pending" | "sold";
export type Drivetrain = "4x4" | "AWD" | "FWD" | "RWD";
export type Fuel = "Gas" | "Diesel" | "Flex Fuel" | "Hybrid" | "Electric";

export type VehicleImage = {
  src: string;
  width: number;
  height: number;
  /** Tiny base64 preview for the blur-up effect (generated by `npm run photos`) */
  blur?: string;
  alt?: string;
};

export type Vehicle = {
  /** Carsforsale listing id. Higher = listed more recently (used for "Newest" sort). */
  listingId: number;
  year: number;
  make: string;
  model: string;
  trim?: string;
  body: Body;
  /** As the listing words it, e.g. "Crew Cab Pickup", "Mini-Van" */
  bodyStyle?: string;
  price: number | "call";
  miles: number | null;
  status: VehicleStatus;

  exterior?: string;
  interior?: string;
  engine?: string;
  transmission?: string;
  drivetrain?: Drivetrain;
  fuel?: Fuel;
  mpg?: { city: number; hwy: number };
  doors?: number;
  seats?: number;
  vin?: string;
  stock?: string;
  titleStatus?: "Clean";

  /** Where it came from, when the listing says (out-of-state = less rust). Two-letter state. */
  origin?: string;
  /** Short, seller-stated facts from the listing description. Nothing invented. */
  highlights?: string[];
  /** The listing description, in the listing's words (phone numbers stripped). */
  description?: string;
  /** A condition caveat the seller states, shown plainly on the page. */
  caveat?: string;
  /** Full options list from the listing */
  features?: string[];

  /** Optional override. Default: year-make-model-trim */
  slug?: string;
  carsForSaleUrl?: string;
  /** Usually left empty: photos are wired in by `npm run photos` (content/photos.generated.ts). */
  images?: VehicleImage[];
};

/** Split a comma-separated options list from the listing into an array. */
export const featureList = (s: string) =>
  s
    .split(/,\s*/)
    .map((f) => f.trim())
    .filter(Boolean);
