/**
 * Greenfield Auto Sales logo — "Speed Badge" lockup.
 *
 *   [hex badge]  GREENFIELD
 *                ───────────
 *                AUTO SALES
 *
 * Badge: chrome G in a red hex, race track running into the distance between
 * two crossed checkered flags (components/brand/Badge.tsx).
 * Wordmark: red-chrome GREENFIELD with a travelling prismatic edge and a
 * light sweep (components/brand/Wordmark.tsx). All inline SVG, no image requests.
 * Art is generated by scripts/brand/gen.py into components/brand/brandPaths.ts.
 */
import Badge from "@/components/brand/Badge";
import Wordmark from "@/components/brand/Wordmark";

type Props = {
  /** "full" = badge + wordmark, "mark" = badge only */
  variant?: "full" | "mark";
  /** Run the prismatic edge + glint. Off for repeated marks (footer). */
  animate?: boolean;
  className?: string;
  /** Tailwind classes sizing the badge / wordmark (heights). */
  badgeClass?: string;
  wordmarkClass?: string;
  /** Small crossed flags on the badge. Off when big flags fly behind the whole lockup (header). */
  badgeFlags?: boolean;
};

export function LogoMark({
  className,
  title,
  flags = true,
  glint = false,
}: {
  className?: string;
  title?: string;
  flags?: boolean;
  glint?: boolean;
}) {
  return <Badge className={className} title={title} flags={flags} glint={glint} />;
}

export default function Logo({
  variant = "full",
  animate = false,
  className,
  badgeClass = "h-12 w-auto",
  wordmarkClass = "h-10 w-auto",
  badgeFlags = true,
}: Props) {
  if (variant === "mark") {
    return <Badge className={className} glint={animate} title="Greenfield Auto Sales" />;
  }
  return (
    <span className={`inline-flex items-center gap-1.5 ${className ?? ""}`}>
      <Badge className={`shrink-0 ${badgeClass}`} glint={animate} flags={badgeFlags} />
      <Wordmark className={`shrink-0 ${wordmarkClass}`} animated={animate} />
      <span className="sr-only">Greenfield Auto Sales</span>
    </span>
  );
}
