#!/usr/bin/env node
/**
 * npm run photos
 *
 * Turns raw listing photos into web-ready images and wires them into the site.
 *
 *   public/inventory/<slug>/raw/*.jpg|png|webp   ← you drop photos here (any names)
 *   public/inventory/<slug>/01.webp, 02.webp…   ← generated (1600px max, WebP)
 *   content/photos.generated.ts                 ← generated (sizes + blur previews)
 *
 * Order = filename order (natural sort), so name them 01.jpg, 02.jpg… or
 * IMG_1001, IMG_1002… The first photo is the card/cover photo.
 * Raw folders are git-ignored; the generated WebP files are committed.
 */
import { readdir, mkdir, writeFile, unlink, stat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const INV = path.join(ROOT, "public", "inventory");
const OUT_TS = path.join(ROOT, "content", "photos.generated.ts");
const MAX_W = 1600;
const QUALITY = 78;
const OK = /\.(jpe?g|png|webp|avif|tiff?)$/i;

const natural = new Intl.Collator(undefined, { numeric: true, sensitivity: "base" }).compare;
const exists = async (p) => !!(await stat(p).catch(() => null));

const result = {};
let total = 0;

await mkdir(INV, { recursive: true });
for (const slug of (await readdir(INV)).sort(natural)) {
  const dir = path.join(INV, slug);
  if (!(await stat(dir)).isDirectory()) continue;
  const raw = path.join(dir, "raw");
  if (!(await exists(raw))) continue;

  const files = (await readdir(raw)).filter((f) => OK.test(f)).sort(natural);
  const skipped = (await readdir(raw)).filter((f) => !OK.test(f) && !f.startsWith("."));
  if (skipped.length) console.warn(`  ${slug}: skipped ${skipped.join(", ")} (convert HEIC to JPG first)`);
  if (!files.length) continue;

  // Clear previous generated output for this car
  for (const f of await readdir(dir)) if (/^\d{2,3}\.webp$/.test(f)) await unlink(path.join(dir, f));

  const images = [];
  for (const [i, f] of files.entries()) {
    const name = `${String(i + 1).padStart(2, "0")}.webp`;
    const img = sharp(path.join(raw, f)).rotate(); // honor camera orientation
    const { data, info } = await img
      .clone()
      .resize({ width: MAX_W, withoutEnlargement: true })
      .webp({ quality: QUALITY })
      .toBuffer({ resolveWithObject: true });
    await writeFile(path.join(dir, name), data);
    const tiny = await img.clone().resize(16).webp({ quality: 40 }).toBuffer();
    images.push({
      src: `/inventory/${slug}/${name}`,
      width: info.width,
      height: info.height,
      blur: `data:image/webp;base64,${tiny.toString("base64")}`,
    });
  }
  result[slug] = images;
  total += images.length;
  console.log(`  ${slug}: ${images.length} photo${images.length === 1 ? "" : "s"}`);
}

const ts = `// Generated by \`npm run photos\`. Do not edit by hand.
import type { VehicleImage } from "./types";

export const photos: Record<string, VehicleImage[]> = ${JSON.stringify(result, null, 2)};
`;
await writeFile(OUT_TS, ts);
console.log(`\nDone: ${total} photos across ${Object.keys(result).length} vehicles → content/photos.generated.ts`);
